### ISSUE TITLE
Transfer request

### ISSUE THREAD

**Issue by quininer** [slp/io-uring#2]
Hi, this library does not seem to be actively maintained, and I am developing a [replacement](https://github.com/quininer/linux-io-uring). would you like to transfer this name to me on crates.io?

**Comment by slp** [comment]
Yes, that makes sense. What's your username in crates.io?

**Comment by quininer** [comment]
My username is [quininer](https://crates.io/users/quininer), thanks you.

**Comment by quininer** [comment]
I close this issue now. Thanks again.
